# site settings
title: SmartCT
description: "putting citizens and data at the heart of smart city building"
email: "info@smartct.org"
baseurl: ""
logo: "/assets/img/site/main.webp"
favicon: favicon.ico
repo_address: "smartctph/smartctph.github.io"
messenger: ""
facebook: "SmartCTorg"
twitter: ""
instagram: ""
mastodon: ""
telegram: ""
github: "smartctph"


# exclude
exclude:
    - .gitignore
    - Gemfile
    - Gemfile.lock

# build settings
markdown: kramdown
highlighter: rouge
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

# plugins
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
